# -*- coding: utf-8 -*-
"""final-CodeForImpact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAONq4_TFrp2ICLfkzL5uT4YE8TzuLMa
"""

!pip install ultralytics

# create data.yamlfor yolo
import yaml
import os

PATCHED_DIR = "/content/drive/MyDrive/patched_dataset"  # your dataset path
DATA_YAML = os.path.join(PATCHED_DIR, "data.yaml")

data_dict = {
    "path": PATCHED_DIR,
    "train": os.path.join(PATCHED_DIR, "images/train"),
    "val": os.path.join(PATCHED_DIR, "images/val"),
    "names": ["dot"]
}

# Write YAML
with open(DATA_YAML, "w") as f:
    yaml.dump(data_dict, f, default_flow_style=False)

print("✅ data.yaml created at:", DATA_YAML)

# Actual Training
from ultralytics import YOLO
import os

MODEL = "yolov8n.pt"
DATA_DICT = "/content/drive/MyDrive/patched_dataset/data.yaml"
RUN_DICT = "/content/drive/MyDrive/patched_dataset/runs"
IMG_SIZE = 512
EPOCHS = 100
BATCH = 4
DEVICE = 0  # GPU

# ===== INITIALIZE MODEL =====
model = YOLO(MODEL)

# ===== TRAIN YOLOv8 =====
results = model.train(
    name="braille-yolo",
    data=DATA_DICT,
    project=RUN_DICT,
    imgsz=IMG_SIZE,
    epochs=EPOCHS,
    batch=BATCH,
    device=DEVICE,
    save=True,        # saves last.pt and best.pt
    save_period=5     # saves checkpoint every 5 epochs
)

print("✅ Training complete!")
print("Best model saved at:", results.best)

# If Resume training
RESUME_WEIGHTS = "/content/drive/MyDrive/patched_dataset/runs/braille-yolo/weights/last.pt"
from ultralytics import YOLO
model = YOLO(RESUME_WEIGHTS)

results = model.train(
    resume=True,   # 🔑 this is critical
    device=0
)

# result/testing
import matplotlib.pyplot as plt
from ultralytics import YOLO
import cv2  # You can still use OpenCV in Colab for image loading

# Define the path to the best model
best_model_path = "/content/drive/MyDrive/patched_dataset/runs/braille-yolo/weights/best.pt"
model = YOLO(best_model_path)

# Path to one image in the validation dataset
image_path = "/content/drive/MyDrive/patched_dataset/images/val/IMG_20260120_163828_jpg.rf.a10d9d77917aa051664bf105da0d2dc9_103.jpg"  # Change to an image from your dataset
# image_path = "/content/drive/MyDrive/compressed_images/IMG_20260120_163522.jpg"  # Change to an image from your dataset

# Perform prediction
results = model.predict(image_path, conf=0.5)  # Adjust conf threshold if needed

# Get prediction details (bounding boxes, labels, and confidences)
predicted_boxes = results[0].boxes  # Get the predicted bounding boxes

# Load the image using OpenCV and convert it to RGB for displaying with matplotlib
image = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Plot the image and predictions
plt.figure(figsize=(10, 8))
plt.imshow(image_rgb)

# Draw the bounding boxes and labels
for box in predicted_boxes:
    # Move the tensor to CPU and convert to NumPy
    x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()  # Coordinates of the bounding box
    confidence = box.conf[0].cpu().numpy()  # Confidence score
    label = box.cls[0].cpu().numpy()  # Label index (you can map this to a label name from your dataset)

    # Draw the box and label with opacity (alpha)
    plt.gca().add_patch(plt.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        fill=True, color='red', linewidth=2, alpha=0.3  # Adjust alpha for opacity
    ))

    # plt.text(x1, y1, f"Class: {label} Conf: {confidence:.2f}",
    #          fontsize=12, color='yellow', bbox=dict(facecolor='black', alpha=0.5))

plt.axis('off')
plt.show()

# Find dots from image
import cv2
import numpy as np
import matplotlib.pyplot as plt
import torch
from torchvision.ops import nms
from ultralytics import YOLO

# -------------------------------
# Load YOLO model
# -------------------------------
best_model_path = "/content/drive/MyDrive/patched_dataset/runs/braille-yolo/weights/best.pt"
model = YOLO(best_model_path)

# -------------------------------
# Parameters
# -------------------------------
IMAGE_PATH = "/content/drive/MyDrive/compressed_images/IMG_20260120_163522.jpg"
# IMAGE_PATH = "/content/drive/MyDrive/compressed_images/IMG_20260120_164418.jpg"
# IMAGE_PATH = "/content/drive/MyDrive/compressed_images/CamScanner 22-01-2026 14.32_1 (1).jpg"
IMAGE_PATH = "/content/drive/MyDrive/compressed_images/IMG_20260120_163542.png"

TILE_SIZE = 256
STRIDE = int(TILE_SIZE * 0.75)  # 192 ~25% overlap
CONF_THRESH = 0.5
MAX_ASPECT_RATIO = 1.2     # square tolerance
NMS_IOU = 0.2              # aggressive overlap removal

# -------------------------------
# Load image
# -------------------------------
image = cv2.imread(IMAGE_PATH)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
H, W, _ = image.shape
# -------------------------------
# Rotate image 180° clockwise
# -------------------------------
image = cv2.rotate(image, cv2.ROTATE_180)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

H, W, _ = image.shape


final_boxes = []
final_scores = []
final_classes = []

# -------------------------------
# Tile-based detection
# -------------------------------
for y in range(0, H, STRIDE):
    for x in range(0, W, STRIDE):

        tile = image[y:y + TILE_SIZE, x:x + TILE_SIZE]

        if tile.shape[0] < 50 or tile.shape[1] < 50:
            continue

        tile_rgb = cv2.cvtColor(tile, cv2.COLOR_BGR2RGB)

        results = model.predict(tile_rgb, conf=CONF_THRESH, verbose=False)

        if results[0].boxes is None:
            continue

        for box in results[0].boxes:
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
            conf = float(box.conf[0])
            cls = int(box.cls[0])

            w = x2 - x1
            h = y2 - y1

            # -------------------------------
            # Reject non-square detections
            # -------------------------------
            aspect_ratio = max(w, h) / min(w, h)
            if aspect_ratio > MAX_ASPECT_RATIO:
                continue

            # -------------------------------
            # Convert to square box
            # -------------------------------
            side = max(w, h)
            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2

            x1_sq = cx - side / 2
            y1_sq = cy - side / 2
            x2_sq = cx + side / 2
            y2_sq = cy + side / 2

            # -------------------------------
            # Map back to original image
            # -------------------------------
            final_boxes.append([
                x1_sq + x,
                y1_sq + y,
                x2_sq + x,
                y2_sq + y
            ])
            final_scores.append(conf)
            final_classes.append(cls)

# -------------------------------
# Apply Global NMS
# -------------------------------
if len(final_boxes) > 0:
    boxes = torch.tensor(final_boxes, dtype=torch.float32)
    scores = torch.tensor(final_scores)

    keep = nms(boxes, scores, iou_threshold=NMS_IOU)

    final_boxes = boxes[keep].numpy()
    final_scores = scores[keep].numpy()
    final_classes = np.array(final_classes)[keep.numpy()]

print(f"Final dot detections: {len(final_boxes)}")

# -------------------------------
# Visualization
# -------------------------------
plt.figure(figsize=(12, 10))
plt.imshow(image_rgb)

for box in final_boxes:
    x1, y1, x2, y2 = box
    plt.gca().add_patch(
        plt.Rectangle(
            (x1-1, y1-1),
            x2 - x1-2,
            y2 - y1-2,
            edgecolor="red",
            facecolor="red",
            linewidth=0.05,
            alpha=0.3
        )
    )

plt.axis("off")
plt.show()

# -------------------------------
# Rotate boxes back 180°
# -------------------------------
rotated_back_boxes = []

for box in final_boxes:
    x1, y1, x2, y2 = box

    x1r = W - x2
    y1r = H - y2
    x2r = W - x1
    y2r = H - y1

    rotated_back_boxes.append([x1r, y1r, x2r, y2r])

final_boxes = np.array(rotated_back_boxes)
# -------------------------------
# Convert boxes to dot centers
# -------------------------------
dots = []

for box in final_boxes:
    x1, y1, x2, y2 = box
    cx = (x1 + x2) / 2
    cy = (y1 + y2) / 2
    dots.append((cx, cy))

print(f"Total dot centers: {len(dots)}")

# dots to grids matching
import numpy as np
import cv2
import matplotlib.pyplot as plt

def braille_grid_detection(points, theta, D_dis):
    """
    Implements the Braille Character Recognition algorithm to detect the grid for characters.

    Parameters:
    - points: list or array of shape (N, 2) containing (x, y) coordinates of detected Braille dots.
    - theta: Threshold for grouping dots into horizontal/vertical lines.
    - D_dis: Threshold distance between intersection points and detected dots.

    Returns:
    - b_cell_info: List of (x, y) tuples representing the occupied Braille grid coordinate points.
    """
    points = np.array(points)
    if points.ndim != 2 or points.shape[1] != 2:
        raise ValueError("Points must be a list or array of (x, y) coordinates.")

    # Step 1: Group points into horizontal lines
    # Sort points by y-coordinate
    sorted_idx_h = np.argsort(points[:, 1])
    sorted_points_h = points[sorted_idx_h]

    hor_groups = []
    current_group = [sorted_points_h[0]]
    for p in sorted_points_h[1:]:
        if abs(p[1] - current_group[-1][1]) <= theta:  # Note: Using <= to include boundary
            current_group.append(p)
        else:
            if len(current_group) >= 2:  # Need at least 2 points to fit a line
                hor_groups.append(np.array(current_group))
            current_group = [p]
    if len(current_group) >= 2:
        hor_groups.append(np.array(current_group))

    # Fit horizontal line equations: y = m_h * x + b_h
    hor_lines = []
    for group in hor_groups:
        x = group[:, 0]
        y = group[:, 1]
        m_h, b_h = np.polyfit(x, y, 1)
        hor_lines.append((m_h, b_h))

    # Step 2: Group points into vertical lines
    # Sort points by x-coordinate
    sorted_idx_v = np.argsort(points[:, 0])
    sorted_points_v = points[sorted_idx_v]

    ver_groups = []
    current_group = [sorted_points_v[0]]
    for p in sorted_points_v[1:]:
        if abs(p[0] - current_group[-1][0]) <= theta:
            current_group.append(p)
        else:
            if len(current_group) >= 2:
                ver_groups.append(np.array(current_group))
            current_group = [p]
    if len(current_group) >= 2:
        ver_groups.append(np.array(current_group))

    # Fit vertical line equations: x = m_v * y + b_v
    ver_lines = []
    for group in ver_groups:
        y = group[:, 1]
        x = group[:, 0]
        m_v, b_v = np.polyfit(y, x, 1)
        ver_lines.append((m_v, b_v))

    # Step 3: Calculate intersection points (pseudo Braille grid points)
    in_points = []
    for m_h, b_h in hor_lines:
        for m_v, b_v in ver_lines:
            denom = 1 - m_h * m_v
            if abs(denom) < 1e-10:
                continue  # Lines are approximately parallel, skip
            y = (m_h * b_v + b_h) / denom
            x = m_v * y + b_v
            in_points.append([x, y])
    in_points = np.array(in_points)

    # Step 4: Match detected dots to intersection points and remove superfluous points
    b_cell_info = []
    for in_p in in_points:
        distances = np.sqrt(np.sum((in_p - points)**2, axis=1))
        if np.any(distances < D_dis):
            b_cell_info.append(tuple(in_p))

    # Remove potential duplicates due to floating-point precision (optional, using a tolerance)
    if b_cell_info:
        b_cell_info = np.array(b_cell_info)
        unique_idx = np.unique(np.round(b_cell_info, decimals=5), axis=0, return_index=True)[1]
        b_cell_info = [tuple(p) for p in b_cell_info[unique_idx]]

    return b_cell_info

# Example usage with sample data
# IMAGE_PATH = 'braille_image.jpg'  # Replace with your actual image path
# dots = [(10, 20), (30, 21), (50, 19), (11, 40), (31, 41), (51, 39)]  # Sample detected dots from YOLOv8
theta = 5.0
D_dis = 3.0

# Compute grid points
B_cell_info = braille_grid_detection(dots, theta, D_dis)

# Load image and overlay points
img = cv2.imread(IMAGE_PATH)
if img is None:
    # If no real image, create a blank one for demo (adjust size as needed)
    img = np.ones((100, 100, 3), dtype=np.uint8) * 255  # White background

# Draw detected dots in red
for (x, y) in dots:
    cv2.circle(img, (int(x), int(y)), 5, (0, 0, 255), -1)  # Red dots

# Draw grid points in green
for (x, y) in B_cell_info:
    cv2.circle(img, (int(x), int(y)), 5, (0, 255, 0), -1)  # Green grid

# Display the image
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.title('Braille Validation: Red = Detected Dots, Green = Grid Points')
plt.show()

# grid into numbers
import numpy as np
import cv2
import matplotlib.pyplot as plt

def braille_grid_detection(points, theta, D_dis):
    """
    Implements the Braille Character Recognition algorithm to detect the grid for characters.

    Parameters:
    - points: list or array of shape (N, 2) containing (x, y) coordinates of detected Braille dots.
    - theta: Threshold for grouping dots into horizontal/vertical lines.
    - D_dis: Threshold distance between intersection points and detected dots.

    Returns:
    - b_cell_info: List of (x, y) tuples representing the occupied Braille grid coordinate points.
    - braille_bins: List of lists, where each sublist contains strings like '1,0,0,0,0,0' for each cell in a line.
    """
    points = np.array(points)
    if points.ndim != 2 or points.shape[1] != 2:
        raise ValueError("Points must be a list or array of (x, y) coordinates.")

    # Step 1: Group points into horizontal lines
    sorted_idx_h = np.argsort(points[:, 1])
    sorted_points_h = points[sorted_idx_h]

    hor_groups = []
    current_group = [sorted_points_h[0]]
    for p in sorted_points_h[1:]:
        if abs(p[1] - current_group[-1][1]) <= theta:
            current_group.append(p)
        else:
            if len(current_group) >= 2:
                hor_groups.append(np.array(current_group))
            current_group = [p]
    if len(current_group) >= 2:
        hor_groups.append(np.array(current_group))

    # Fit horizontal line equations: y = m_h * x + b_h
    hor_lines = []
    hor_avg_y = []
    for group in hor_groups:
        x = group[:, 0]
        y = group[:, 1]
        m_h, b_h = np.polyfit(x, y, 1)
        hor_lines.append((m_h, b_h))
        hor_avg_y.append(np.mean(y))

    # Sort horizontal lines by average y (top to bottom, assuming y increases downward)
    indices_h = np.argsort(hor_avg_y)
    hor_lines_sorted = [hor_lines[i] for i in indices_h]
    hor_avg_y_sorted = [hor_avg_y[i] for i in indices_h]

    # Step 2: Group points into vertical lines
    sorted_idx_v = np.argsort(points[:, 0])
    sorted_points_v = points[sorted_idx_v]

    ver_groups = []
    current_group = [sorted_points_v[0]]
    for p in sorted_points_v[1:]:
        if abs(p[0] - current_group[-1][0]) <= theta:
            current_group.append(p)
        else:
            if len(current_group) >= 2:
                ver_groups.append(np.array(current_group))
            current_group = [p]
    if len(current_group) >= 2:
        ver_groups.append(np.array(current_group))

    # Fit vertical line equations: x = m_v * y + b_v
    ver_lines = []
    ver_avg_x = []
    for group in ver_groups:
        y = group[:, 1]
        x = group[:, 0]
        m_v, b_v = np.polyfit(y, x, 1)
        ver_lines.append((m_v, b_v))
        ver_avg_x.append(np.mean(x))

    # Sort vertical lines by average x (left to right)
    indices_v = np.argsort(ver_avg_x)
    ver_lines_sorted = [ver_lines[i] for i in indices_v]
    ver_avg_x_sorted = [ver_avg_x[i] for i in indices_v]

    # Step 3: Calculate all intersection points
    in_points = []
    for m_h, b_h in hor_lines_sorted:
        for m_v, b_v in ver_lines_sorted:
            denom = 1 - m_h * m_v
            if abs(denom) < 1e-10:
                continue
            y = (m_h * b_v + b_h) / denom
            x = m_v * y + b_v
            in_points.append((x, y))
    in_points = np.array(in_points)

    # Step 4: Match to occupied points
    b_cell_info = []
    for in_p in in_points:
        distances = np.sqrt(np.sum((in_p - points)**2, axis=1))
        if np.any(distances < D_dis):
            b_cell_info.append(tuple(in_p))

    # Deduplicate
    if b_cell_info:
        b_cell_info = np.array(b_cell_info)
        unique_idx = np.unique(np.round(b_cell_info, decimals=5), axis=0, return_index=True)[1]
        b_cell_info = [tuple(p) for p in b_cell_info[unique_idx]]

    # Prepare rounded set for matching
    b_cell_rounded = set((round(x, 2), round(y, 2)) for x, y in b_cell_info)

    # Step 5: Group horizontal lines into text lines (clusters of 3)
    braille_bins = []
    if len(hor_avg_y_sorted) < 3:
        return b_cell_info, braille_bins

    diffs_h = np.diff(hor_avg_y_sorted)
    median_diff_h = np.median(diffs_h) if len(diffs_h) > 0 else 0
    line_groups = []
    current = [0]
    for i in range(len(diffs_h)):
        if median_diff_h > 0 and diffs_h[i] > 1.5 * median_diff_h:
            line_groups.append(current)
            current = [i + 1]
        else:
            current.append(i + 1)
    line_groups.append(current)

    line_groups = [g for g in line_groups if len(g) == 3]  # Only valid 3-row groups

    # For vertical: assume even number of columns, drop if odd
    num_cols = len(ver_avg_x_sorted)
    num_cols -= num_cols % 2

    if num_cols < 2:
        return b_cell_info, braille_bins

    # Compute median within-cell column spacing
    within_diffs = [ver_avg_x_sorted[2 * j + 1] - ver_avg_x_sorted[2 * j] for j in range(num_cols // 2)]
    median_within = np.median(within_diffs) if within_diffs else 0

    # For each text line
    for group in line_groups:
        hor_lines_this = [hor_lines_sorted[idx] for idx in group]
        cell_bins = []

        for j in range(num_cols // 2):
            # Insert space if large gap to previous cell
            if j > 0:
                between = ver_avg_x_sorted[2 * j] - ver_avg_x_sorted[2 * j - 1]
                if median_within > 0 and between > 2 * median_within:
                    cell_bins.append('0,0,0,0,0,0')

            # Get line params
            m_h1, b_h1 = hor_lines_this[0]
            m_h2, b_h2 = hor_lines_this[1]
            m_h3, b_h3 = hor_lines_this[2]
            m_vl, b_vl = ver_lines_sorted[2 * j]
            m_vr, b_vr = ver_lines_sorted[2 * j + 1]

            # Compute intersection
            def get_intersect(m_h, b_h, m_v, b_v):
                denom = 1 - m_h * m_v
                if abs(denom) < 1e-10:
                    return None
                y = (m_h * b_v + b_h) / denom
                x = m_v * y + b_v
                return (x, y)

            pos1 = get_intersect(m_h1, b_h1, m_vl, b_vl)
            pos2 = get_intersect(m_h2, b_h2, m_vl, b_vl)
            pos3 = get_intersect(m_h3, b_h3, m_vl, b_vl)
            pos4 = get_intersect(m_h1, b_h1, m_vr, b_vr)
            pos5 = get_intersect(m_h2, b_h2, m_vr, b_vr)
            pos6 = get_intersect(m_h3, b_h3, m_vr, b_vr)

            pos_list = [pos1, pos2, pos3, pos4, pos5, pos6]
            bin_list = []
            for pos in pos_list:
                if pos is None:
                    bin_list.append(0)
                    continue
                r_pos = (round(pos[0], 2), round(pos[1], 2))
                bin_list.append(1 if r_pos in b_cell_rounded else 0)

            cell_bins.append(','.join(map(str, bin_list)))

        braille_bins.append(cell_bins)

    return b_cell_info, braille_bins

# Example usage with sample data (note: sample has 2 rows, so no valid 3-row groups; use real data)
# IMAGE_PATH = 'braille_image.jpg'  # Replace with your actual image path
# dots = []  # Replace with your actual list of (x, y) from YOLOv8 detections
theta = 5.0  # Adjust based on your data
D_dis = 3.0  # Adjust based on your data

# Compute grid and binary representations
B_cell_info, braille_bins = braille_grid_detection(dots, theta, D_dis)

# Print the binary representations (per line, space-separated cells)
print("Braille Binary Representations:")
for i, line in enumerate(braille_bins):
    print(f"Line {i+1}: {' '.join(line)}")

# Load image and overlay points for validation
img = cv2.imread(IMAGE_PATH)
if img is None:
    img = np.ones((100, 100, 3), dtype=np.uint8) * 255  # Blank if no image

for (x, y) in dots:
    cv2.circle(img, (int(x), int(y)), 5, (0, 0, 255), -1)  # Red dots

for (x, y) in B_cell_info:
    cv2.circle(img, (int(x), int(y)), 5, (0, 255, 0), -1)  # Green grid

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.title('Braille Validation: Red = Detected Dots, Green = Grid Points')
plt.show()

# Numbers to text (OBR)
# ---------- Braille bit helpers ----------

def dots_to_bit(dots):
    """Convert braille dot numbers [1..6] to integer bitmask"""
    value = 0
    for d in dots:
        value |= (1 << (d - 1))
    return value


def bits_to_int(bits):
    """Convert [0,1,0,1,0,0] → integer bitmask"""
    value = 0
    for i, b in enumerate(bits):
        if b:
            value |= (1 << i)
    return value


# ---------- Bharati Braille Map ----------

braille_map = {
    dots_to_bit([1]): 'अ',
    dots_to_bit([3, 4, 5]): 'आ',
    dots_to_bit([2, 4]): 'इ',
    dots_to_bit([3, 5]): 'ई',
    dots_to_bit([1, 3, 6]): 'उ',
    dots_to_bit([1, 2, 5, 6]): 'ऊ',
    dots_to_bit([1, 5, 6]): 'ऋ',
    dots_to_bit([1, 5]): 'ए',
    dots_to_bit([3, 4]): 'ऐ',
    dots_to_bit([1, 3, 5]): 'ओ',
    dots_to_bit([2, 4, 6]): 'औ',
    dots_to_bit([1, 6]): 'अं',
    dots_to_bit([6]): 'अः',

    dots_to_bit([1, 3]): 'क',
    dots_to_bit([4, 6]): 'ख',
    dots_to_bit([1, 2, 4, 5]): 'ग',
    dots_to_bit([1, 2, 6]): 'घ',
    dots_to_bit([3, 4, 6]): 'ङ',
    dots_to_bit([1, 4]): 'च',
    dots_to_bit([1, 6]): 'छ',
    dots_to_bit([2, 4, 5]): 'ज',
    dots_to_bit([3, 5, 6]): 'झ',
    dots_to_bit([2, 5]): 'ञ',
    dots_to_bit([2, 3, 4, 6]): 'ट',
    dots_to_bit([2, 4, 5, 6]): 'ठ',
    dots_to_bit([1, 2, 4, 6]): 'ड',
    dots_to_bit([1, 2, 3, 4, 6]): 'ढ',
    dots_to_bit([3, 4, 5, 6]): 'ण',
    dots_to_bit([2, 3, 4, 5]): 'त',
    dots_to_bit([1, 4, 5, 6]): 'थ',
    dots_to_bit([1, 4, 5]): 'द',
    dots_to_bit([2, 3, 5, 6]): 'ध',
    dots_to_bit([1, 3, 4, 5]): 'न',
    dots_to_bit([1, 2, 3, 4]): 'प',
    dots_to_bit([2, 3, 5]): 'फ',
    dots_to_bit([1, 2]): 'ब',
    dots_to_bit([4, 5]): 'भ',
    dots_to_bit([1, 3, 4]): 'म',
    dots_to_bit([1, 3, 4, 5, 6]): 'य',
    dots_to_bit([1, 2, 3, 5]): 'र',
    dots_to_bit([1, 2, 3]): 'ल',
    dots_to_bit([1, 2, 3, 6]): 'व',
    dots_to_bit([1, 4, 6]): 'श',
    dots_to_bit([1, 2, 3, 4, 6]): 'ष',
    dots_to_bit([2, 3, 4]): 'स',
    dots_to_bit([1, 2, 5]): 'ह',
    dots_to_bit([1, 2, 3, 4, 5]): 'क्ष',
    dots_to_bit([1, 5, 6]): 'ज्ञ',
}


# ---------- Braille Decoder ----------

def decode_braille_lines(braille_bins, braille_map):
    """
    braille_bins: List[List[str]]  (output of braille_grid_detection)
    """
    decoded_lines = []

    for line in braille_bins:
        line_text = []
        for cell in line:
            bits = [int(b) for b in cell.split(',')]

            # Space
            if bits == [0, 0, 0, 0, 0, 0]:
                line_text.append(' ')
                continue

            key = bits_to_int(bits)
            line_text.append(braille_map.get(key, '�'))

        decoded_lines.append(''.join(line_text).rstrip())

    return '\n'.join(decoded_lines)


# ---------- Usage ----------

# B_cell_info, braille_bins = braille_grid_detection(dots, theta, D_dis)
decoded_text = decode_braille_lines(braille_bins, braille_map)
print(decoded_text)