# -*- coding: utf-8 -*-
"""new-braille

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7lrsBNsWJsRPr-IJrpTKNOPxF26Lurr
"""

# !pip install ultralytics -q

import yaml
import os

# Dataset root
PATCHED_DIR = "/content/drive/MyDrive/dataset_2"

# YAML file path
DATA_YAML = os.path.join(PATCHED_DIR, "data.yaml")

# YOLO dataset configuration
data_dict = {
    "path": PATCHED_DIR,

    # dataset splits
    "train": "train/images",
    "val": "val/images",
    "test": "test/images",

    # classes
    "nc": 1,
    "names": ["dots"]
}

# Save YAML
with open(DATA_YAML, "w") as f:
    yaml.dump(data_dict, f, default_flow_style=False)

print("✅ data.yaml created at:", DATA_YAML)

# Install Ultralytics
# !pip install ultralytics -q

from ultralytics import YOLO
import os

# =========================
# PATHS
# =========================
DATASET_DIR = "/content/drive/MyDrive/dataset_2"
DATA_YAML = os.path.join(DATASET_DIR, "data.yaml")

# Where training runs will be stored
RUNS_DIR = os.path.join(DATASET_DIR, "runs")

# =========================
# TRAINING SETTINGS
# =========================
IMG_SIZE = 512
EPOCHS = 100
BATCH = 4
DEVICE = 0   # GPU

# =========================
# CHOOSE MODEL
# =========================
# yolov8n.pt = Nano
# yolov8s.pt = Small
# yolov8m.pt = Medium

MODEL_NAME = "yolov8n.pt"

# =========================
# INITIALIZE MODEL
# =========================
model = YOLO(MODEL_NAME)

# =========================
# TRAIN
# =========================
results = model.train(
    data=DATA_YAML,
    project=RUNS_DIR,
    name="braille-yolo",

    imgsz=IMG_SIZE,
    epochs=EPOCHS,
    batch=BATCH,
    device=DEVICE,

    save=True,
    save_period=5
)

print("✅ Training complete!")

from ultralytics import YOLO
import os

RESUME_WEIGHTS = "/content/drive/MyDrive/dataset_2/runs/braille-yolo/weights/last.pt"

model = YOLO(RESUME_WEIGHTS)

results = model.train(
    resume=True,
    device=0
)

print("✅ Resume training complete!")

# ============================================
# YOLOv8 COMPLETE EVALUATION + VISUALIZATION
# ============================================

# !pip install ultralytics -q

from ultralytics import YOLO
from IPython.display import Image, display
import pandas as pd
import os

# ============================================
# PATHS
# ============================================

RUN_DIR = "/content/drive/MyDrive/dataset_2/runs/braille-yolo"
BEST_MODEL = os.path.join(RUN_DIR, "weights/best.pt")

# ============================================
# LOAD MODEL
# ============================================

model = YOLO(BEST_MODEL)

# ============================================
# VALIDATE MODEL
# ============================================

metrics = model.val(split="test")

print("\n✅ MODEL EVALUATION COMPLETE\n")

# ============================================
# PRINT IMPORTANT METRICS
# ============================================

print("Precision :", metrics.box.mp)
print("Recall    :", metrics.box.mr)
print("mAP50     :", metrics.box.map50)
print("mAP50-95  :", metrics.box.map)

# ============================================
# DISPLAY GENERATED GRAPHS
# ============================================

graphs = [
    "results.png",
    "confusion_matrix.png",
    "F1_curve.png",
    "P_curve.png",
    "R_curve.png",
    "PR_curve.png"
]

for graph in graphs:
    graph_path = os.path.join(RUN_DIR, graph)

    if os.path.exists(graph_path):
        print(f"\n📊 Showing: {graph}\n")
        display(Image(filename=graph_path))
    else:
        print(f"❌ Missing: {graph}")

# ============================================
# READ TRAINING CSV
# ============================================

csv_path = os.path.join(RUN_DIR, "results.csv")

if os.path.exists(csv_path):

    df = pd.read_csv(csv_path)

    print("\n📄 LAST 5 TRAINING EPOCHS:\n")
    print(df.tail())

else:
    print("❌ results.csv not found")

# ============================================
# RUN PREDICTIONS ON TEST IMAGES
# ============================================

print("\n🔍 Running predictions on test images...\n")

predictions = model.predict(
    source="/content/drive/MyDrive/dataset_2/test/images",
    save=True,
    conf=0.25
)

print("\n✅ Predictions saved in runs/detect/predict/")